include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
#    implicit-dynamic: false
  errors:
    # Increase the severity of the unused_import hint.
    unused_import: warning
    invalid_assignment: warning
    missing_return: error
    dead_code: info
  exclude:
    - test/data/**
linter:
  rules:
    - empty_statements
    - unnecessary_brace_in_string_interps