name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8.0_241'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.13+hotfix.9'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
