name: Pipeline

on:
  push:
    branches: [ master, release, develop ]
  pull_request:
    branches: [ master, release, develop ]

env:
  flutter_version: "2.0.1"
  java_version: "12.x"
  ruby-version: "2.7.2"

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - run: flutter pub get
      - run: flutter test
      - run: flutter build appbundle -t lib/environments/integration.dart --debug

  tag:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1

      - name: Create a new tag
        id: tag_version
        uses: jacopo1395/action-autotag@2.0.3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/setup-java@v1
        if: ${{ steps.tag_version.outputs.tagname }}
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - run: flutter pub get
      - run: flutter build apk -t lib/environments/integration.dart --debug

      - name: Create a GitHub release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.tagname }}
          release_name: v${{ steps.tag_version.outputs.tagname }}
          body: ${{ steps.tag_version.outputs.tagmessage }}
          prerelease: github.ref != 'refs/heads/master'

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        id: upload_release_asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./build/app/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/apk

  deploy:
    if:  github.ref != 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'deploy'
          subdirectory: 'android'


